{
  "extends": "stylelint-config-recommended-scss",
  "plugins": [
    "stylelint-scss"
  ],
  "ignoreFiles": [
    "node_modules/**/*.css",
    "css/**/*.css"
  ],
  "rules": {
    # Possible Errors
    "at-rule-no-unknown": true,                                 # Disallow unknown at-rules.
    "block-no-empty": true,                                     # Disallow empty blocks.
    "color-no-invalid-hex": true,                               # Disallow invalid hex colors.
    "comment-no-empty": true,                                   # Disallow empty comments.
    "declaration-block-no-duplicate-properties": true,          # Disallow duplicate properties within declaration blocks.
    "declaration-block-no-shorthand-property-overrides": true,  # Disallow shorthand properties that override related longhand properties within declaration blocks.
    "font-family-no-duplicate-names": true,                     # Disallow duplicate font family names.
    "font-family-no-missing-generic-family-keyword": true,      # Disallow missing generic families in lists of font family names.
    "function-calc-no-unspaced-operator": true,                 # Disallow an unspaced operator within calc() functions.
    "function-linear-gradient-no-nonstandard-direction": true,  # Disallow direction values in linear-gradient() calls that are not valid according to the standard syntax.
    "keyframe-declaration-no-important": true,                  # Disallow !important within keyframe declarations.
    "media-feature-name-no-unknown": true,                      # Disallow unknown media feature names.
    "no-descending-specificity": true,                          # Disallow selectors of lower specificity from coming after overriding selectors of higher specificity.
    "no-duplicate-at-import-rules": true,                       # Disallow duplicate @import rules within a stylesheet.
    "no-duplicate-selectors": true,                             # Disallow duplicate selectors.
    "no-empty-source": true,                                    # Disallow empty sources.
    "no-extra-semicolons": true,                                # Disallow extra semicolons.
    "no-invalid-double-slash-comments": true,                   # Disallow double-slash comments (//...) which are not supported by CSS.
    "property-no-unknown": true,                                # Disallow unknown properties.
    "selector-pseudo-class-no-unknown": true,                   # Disallow unknown pseudo-class selectors.
    "selector-pseudo-element-no-unknown": true,                 # Disallow unknown pseudo-element selectors.
    "selector-type-no-unknown": true,                           # Disallow unknown type selectors.
    "string-no-newline": true,                                  # Disallow (unescaped) newlines in strings.
    "unit-no-unknown": true,                                    # Disallow unknown units.

    # Limit Language Features
    "at-rule-blacklist": ["debug"],                             # Specify a blacklist of disallowed at-rules.
    "at-rule-no-vendor-prefix": true,                           # Disallow vendor prefixes for at-rules.
    "at-rule-whitelist": string|[],                             # Specify a whitelist of allowed at-rules.
    "color-named": "always-where-possible"|"never",             # Require (where possible) or disallow named colors.
    "color-no-hex": true,                                       # Disallow hex colors.
    "comment-word-blacklist": string|[],                        # Specify a blacklist of disallowed words within comments.
    "custom-property-pattern": string,                          # Specify a pattern for custom properties.
    "declaration-block-no-redundant-longhand-properties": true, # Disallow longhand properties that can be combined into one shorthand property.
    "declaration-no-important": true,                           # Disallow !important within declarations.
    "declaration-property-unit-blacklist": {},                  # Specify a blacklist of disallowed property and unit pairs within declarations.
    "declaration-property-unit-whitelist": {},                  # Specify a whitelist of allowed property and unit pairs within declarations.
    "declaration-property-value-blacklist": {},                 # Specify a blacklist of disallowed property and value pairs within declarations.
    "declaration-property-value-whitelist": {},                 # Specify a whitelist of allowed property and value pairs within declarations.
    "declaration-block-single-line-max-declarations": int,      # Limit the number of declaration within single line declaration blocks.
    "function-blacklist": string|[],                            # Specify a blacklist of disallowed functions.
    "function-url-no-scheme-relative": true,                    # Disallow scheme-relative urls.
    "function-url-scheme-blacklist": string|[],                 # Specify a blacklist of disallowed url schemes.
    "function-url-scheme-whitelist": string|[],                 # Specify a whitelist of allowed url schemes.
    "function-whitelist": string|[],                            # Specify a whitelist of allowed functions.
    "max-nesting-depth": int,                                   # Limit the depth of nesting.
    "media-feature-name-blacklist": string|[],                  # Specify a blacklist of disallowed media feature names.
    "media-feature-name-no-vendor-prefix": true,                # Disallow vendor prefixes for media feature names.
    "media-feature-name-whitelist": string|[],                  # Specify a whitelist of allowed media feature names.
    "no-unknown-animations": true,                              # Disallow unknown animations.
    "number-max-precision": int,                                # Limit the number of decimal places allowed in numbers.
    "property-blacklist": string|[],                            # Specify a blacklist of disallowed properties.
    "property-no-vendor-prefix": true,                          # Disallow vendor prefixes for properties.
    "property-whitelist": string|[],                            # Specify a whitelist of allowed properties.
    "selector-attribute-operator-blacklist": string|[],         # Specify a blacklist of disallowed attribute operators.
    "selector-attribute-operator-whitelist": string|[],         # Specify a whitelist of allowed attribute operators.
    "selector-class-pattern": string,                           # Specify a pattern for class selectors.
    "selector-combinator-blacklist": string|[],                 # Specify a blacklist of disallowed combinators.
    "selector-combinator-whitelist": string|[],                 # Specify a whitelist of allowed combinators.
    "selector-id-pattern": string,                              # Specify a pattern for id selectors.
    "selector-max-attribute": int,                              # Limit the number of attribute selectors in a selector.
    "selector-max-class": int,                                  # Limit the number of classes in a selector.
    "selector-max-combinators": int,                            # Limit the number of combinators in a selector.
    "selector-max-compound-selectors": int,                     # Limit the number of compound selectors in a selector.
    "selector-max-empty-lines": int,                            # Limit the number of adjacent empty lines within selectors.
    "selector-max-id": int,                                     # Limit the number of id selectors in a selector.
    "selector-max-specificity": string,                         # Limit the specificity of selectors.
    "selector-max-type": int,                                   # Limit the number of type in a selector.
    "selector-max-universal": int,                              # Limit the number of universal selectors in a selector.
    "selector-nested-pattern": string,                          # Specify a pattern for the selectors of rules nested within rules.
    "selector-no-qualifying-type": true,                        # Disallow qualifying a selector by type.
    "selector-no-vendor-prefix": true,                          # Disallow vendor prefixes for selectors.
    "selector-pseudo-class-blacklist": string|[],               # Specify a blacklist of disallowed pseudo-class selectors.
    "selector-pseudo-class-whitelist": string|[],               # Specify a whitelist of allowed pseudo-class selectors.
    "selector-pseudo-element-blacklist": string|[],             # Specify a blacklist of disallowed pseudo-element selectors.
    "selector-pseudo-element-whitelist": string|[],             # Specify a whitelist of allowed pseudo-element selectors.
    "shorthand-property-no-redundant-values": true,             # Disallow redundant values in shorthand properties (Autofixable).
    "time-min-milliseconds": int,                               # Specify the minimum number of milliseconds for time values.
    "unit-blacklist": string|[],                                # Specify a blacklist of disallowed units.
    "unit-whitelist": string|[],                                # Specify a whitelist of allowed units.
    "value-no-vendor-prefix": true,                             # Disallow vendor prefixes for values.

    # Stylistic Issues
    "at-rule-empty-line-before": "always"|"never",
    "at-rule-name-case": "lower"|"upper",
    "at-rule-name-newline-after": "always"|"always-multi-line",
    "at-rule-name-space-after": "always"|"always-single-line",
    "at-rule-semicolon-newline-after": "always",
    "at-rule-semicolon-space-before": "always"|"never",
    "block-closing-brace-empty-line-before": "always-multi-line"|"never",
    "block-closing-brace-newline-after": "always"|"always-single-line"|"never-single-line"|"always-multi-line"|"never-multi-line",
    "block-closing-brace-newline-before": "always"|"always-multi-line"|"never-multi-line",
    "block-closing-brace-space-after": "always"|"always-single-line"|"never-single-line"|"always-multi-line"|"never-multi-line",
    "block-closing-brace-space-before": "always"|"never"|"always-single-line"|"never-single-line"|"always-multi-line"|"never-multi-line",
    "block-opening-brace-newline-after": "always"|"always-multi-line"|"never-multi-line",
    "block-opening-brace-newline-before": "always"|"always-single-line"|"never-single-line"|"always-multi-line"|"never-multi-line",
    "block-opening-brace-space-after": "always"|"always-single-line"|"never-single-line"|"always-multi-line"|"never-multi-line",
    "block-opening-brace-space-before": "always"|"always-single-line"|"never-single-line"|"always-multi-line"|"never-multi-line",
    "color-hex-case": "lower"|"upper",
    "color-hex-length": "short"|"long",
    "comment-empty-line-before": "always"|"never",
    "comment-no-empty": true,
    "comment-whitespace-inside": "always"|"never",
    "custom-property-empty-line-before": "always"|"never",
    "declaration-bang-space-after": "always"|"never",
    "declaration-bang-space-before": "always"|"never",
    "declaration-block-semicolon-newline-after": "always"|"always-multi-line"|"never-multi-line",
    "declaration-block-semicolon-newline-before": "always"|"always-multi-line"|"never-multi-line",
    "declaration-block-semicolon-space-after": "always"|"never"|"always-single-line"|"never-single-line",
    "declaration-block-semicolon-space-before": "always"|"never"|"always-single-line"|"never-single-line",
    "declaration-block-trailing-semicolon": "always"|"never",
    "declaration-colon-newline-after": "always"|"always-multi-line",
    "declaration-colon-space-after": "always"|"never"|"always-single-line",
    "declaration-colon-space-before": "always"|"never",
    "declaration-empty-line-before": "always"|"never",
    "font-family-name-quotes": "always-where-required"|"always-where-recommended"|"always-unless-keyword",
    "font-weight-notation": "numeric"|"named",
    "function-comma-newline-after": "always"|"always-multi-line"|"never-multi-line",
    "function-comma-newline-before": "always"|"always-multi-line"|"never-multi-line",
    "function-comma-space-after": "always"|"never"|"always-single-line"|"never-single-line",
    "function-comma-space-before": "always"|"never"|"always-single-line"|"never-single-line",
    "function-max-empty-lines": int,
    "function-name-case": "lower"|"upper",
    "function-parentheses-newline-inside": "always"|"always-multi-line"|"never-multi-line",
    "function-parentheses-space-inside": "always"|"never"|"always-single-line"|"never-single-line",
    "function-url-quotes": "always"|"never",
    "function-whitespace-after": "always"|"never",
    "indentation": int|"tab",
    "length-zero-no-unit": true,
    "max-empty-lines": int,
    "max-line-length": int,
    "media-feature-colon-space-after": "always"|"never",
    "media-feature-colon-space-before": "always"|"never",
    "media-feature-name-case": "lower"|"upper",
    "media-feature-name-no-unknown": true,
    "media-feature-parentheses-space-inside": "always"|"never",
    "media-feature-range-operator-space-after": "always"|"never",
    "media-feature-range-operator-space-before": "always"|"never",
    "media-query-list-comma-newline-after": "always"|"always-multi-line"|"never-multi-line",
    "media-query-list-comma-newline-before": "always"|"always-multi-line"|"never-multi-line",
    "media-query-list-comma-space-after": "always"|"never"|"always-single-line"|"never-single-line",
    "media-query-list-comma-space-before": "always"|"never"|"always-single-line"|"never-single-line",
    "no-eol-whitespace": true,
    "no-missing-end-of-source-newline": true,
    "number-leading-zero": "always"|"never",
    "number-no-trailing-zeros": true,
    "property-case": "lower"|"upper",
    "rule-empty-line-before": "always"|"never"|"always-multi-line"|"never-multi-line",
    "selector-attribute-brackets-space-inside": "always"|"never",
    "selector-attribute-operator-space-after": "always"|"never",
    "selector-attribute-operator-space-before": "always"|"never",
    "selector-attribute-quotes": "always"|"never",
    "selector-combinator-space-after": "always"|"never",
    "selector-combinator-space-before": "always"|"never",
    "selector-descendant-combinator-no-non-space": true,
    "selector-list-comma-newline-after": "always"|"always-multi-line"|"never-multi-line",
    "selector-list-comma-newline-before": "always"|"always-multi-line"|"never-multi-line",
    "selector-list-comma-space-after": "always"|"never"|"always-single-line"|"never-single-line",
    "selector-list-comma-space-before": "always"|"never"|"always-single-line"|"never-single-line",
    "selector-pseudo-class-case": "lower"|"upper",
    "selector-pseudo-class-parentheses-space-inside": "always"|"never",
    "selector-pseudo-element-case": "lower"|"upper",
    "selector-pseudo-element-colon-notation": "single"|"double",
    "selector-type-case": "lower"|"upper",
    "string-quotes": "single"|"double",
    "unit-case": "lower"|"upper",
    "value-keyword-case": "lower"|"upper",
    "value-list-comma-newline-after": "always"|"always-multi-line"|"never-multi-line",
    "value-list-comma-newline-before": "always"|"always-multi-line"|"never-multi-line",
    "value-list-comma-space-after": "always"|"never"|"always-single-line"|"never-single-line",
    "value-list-comma-space-before": "always"|"never"|"always-single-line"|"never-single-line",
    "value-list-max-empty-lines": int
  },
}
