# Oomph default confog file
# The main focus here is readability & consistency
# most rules domnt matter too much.

{
  "extends": [
    "stylelint-config-recommended-scss",
    "stylelint-config-sass-guidelines",
  ],
  "plugins": [
    "stylelint-order",
    "stylelint-scss"
  ],
  "ignoreFiles": [
    "node_modules/**/*.css",
    "css/**/*.css",
    "sass/vendor/**/*.scss"
  ],
  "rules": {
    "order/properties-alphabetical-order": null,
    "number-leading-zero": [
      "never",
      { "severity": "warning" }
    ],
    "rule-empty-line-before": [
      "always-multi-line",
      {
        "except": ["first-nested"],
        "ignore": ["after-comment"]
      }
    ],
  },
}
